DabesiaWebApp/Controllers/FileController.cs
using DabesiaWebApp.Helpers;
using DabesiaWebApp.Models;
using iText.IO.Image;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Windows;

namespace DabesiaWebApp.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        private readonly DabesiaWebAppContext _context;

        public FileController(DabesiaWebAppContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> DownloadVoucher(int id)
        {
            PurchaseOrder order = await _context.PurchaseOrder.Include(b => b.Product).Include(b => b.Customer).SingleOrDefaultAsync(m => m.OrderID == id);

            Voucher voucher = new Voucher();
            voucher.Create(order.OrderID);
            voucher.AddContent(order);
            voucher.Save();

            var memory = new MemoryStream();
            using (var stream = new FileStream(voucher.FilePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, "application/pdf", Path.GetFileName(voucher.FilePath));
        }

        [HttpPost]
        public async Task<IActionResult> DownloadInvoice(int id)
        {
            PurchaseOrder order = await _context.PurchaseOrder.Include(b => b.Product).Include(b => b.Customer).SingleOrDefaultAsync(m => m.OrderID == id);

            Invoice invoice = new Invoice();
            invoice.Create(order.OrderID);
            invoice.AddContent(order);
            invoice.Save();

            var memory = new MemoryStream();
            using (var stream = new FileStream(invoice.FilePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, "application/vnd.ms-word", Path.GetFileName(invoice.FilePath));
        }
    }
}

DabesiaWebApp/Controllers/OrdersController.cs
using DabesiaWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DabesiaWebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly DabesiaWebAppContext _context;

        public OrdersController(DabesiaWebAppContext context)
        {
            _context = context;
        }

        // GET: Bestellungen
        public async Task<IActionResult> Index(string sortOrder, string searchString, string orderState, DateTime? startDate, DateTime? endDate)
        {
            ViewBag.OrderSortParm = string.IsNullOrEmpty(sortOrder) ? "OrderDesc" : "";
            ViewBag.StateSortParm = sortOrder == "State" ? "StateDesc" : "State";
            ViewBag.DateSortParm = sortOrder == "Date" ? "DateDesc" : "Date";
            ViewBag.CustomerSortParm = sortOrder == "Customer" ? "CustomerDesc" : "Customer";

            IEnumerable<PurchaseOrder> orders = await _context.PurchaseOrder.Include(b => b.Customer).Include(b => b.Product).ToListAsync();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                orders = orders.Where(b =>
                    b.Customer.LastName.ToLower().Contains(searchString.ToLower()) ||
                    b.Customer.FirstName.ToLower().Contains(searchString.ToLower()) ||
                    b.OrderID.ToString().ToLower().Contains(searchString.ToLower()));
                ViewBag.SearchString = searchString;
            }

            if (!string.IsNullOrWhiteSpace(orderState))
            {
                if (orderState != "Alle")
                {
                    orders = orders.Where(b => b.OrderState.ToString() == orderState);
                }
            }

            if (startDate != null)
            {
                if (endDate == null)
                {
                    endDate = DateTime.Today;
                }

                if (startDate <= endDate)
                {
                    orders = orders.Where(b => (b.OrderDate >= startDate && b.OrderDate <= endDate));
                }
                else
                {
                    orders = orders.Where(b => (b.OrderDate <= startDate && b.OrderDate >= endDate));
                }

                ViewBag.StartDate = startDate.Value.Day + "." + startDate.Value.Month + "." + startDate.Value.Year;
                ViewBag.EndDate = endDate.Value.Day + "." + endDate.Value.Month + "." + endDate.Value.Year;
            }

            IOrderedEnumerable<PurchaseOrder> ordersSorted = orders.OrderBy(b => b.OrderID);

            switch (sortOrder)
            {
                case "OrderDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderID);
                    break;
                case "State":
                    ordersSorted = orders.OrderBy(b => b.OrderState);
                    break;
                case "StateDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderState);
                    break;
                case "Date":
                    ordersSorted = orders.OrderBy(b => b.OrderDate);
                    break;
                case "DateDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderDate);
                    break;
                case "Customer":
                    ordersSorted = orders.OrderBy(b => b.Customer.LastName);
                    break;
                case "CustomerDesc":
                    ordersSorted = orders.OrderByDescending(b => b.Customer.LastName);
                    break;
                default:
                    break;
            }

            return View(ordersSorted);
        }

        // GET: Bestellungen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Bestellungen/Create
        public IActionResult Create(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.Customer = id;
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID");
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "ProductID");

            ViewBag.Today = DateTime.Today.Day + "." + DateTime.Today.Month + "." + DateTime.Today.Year;

            return View();
        }

        // POST: Bestellungen/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderDate,CustomerID,ProductID,OrderState,PaymentDate,UsageDate,Discount,VoucherCode,ExpiryDate")] PurchaseOrder order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Description", order.ProductID);

            return View(order);
        }

        // GET: Bestellungen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            ViewBag.OrderDate = order.OrderDate;

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Description", order.ProductID);

            HttpContext.Session.SetInt32("StatusCache", (int)order.OrderState);

            return View(order);
        }

        // POST: Bestellungen/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,OrderDate,CustomerID,ProductID,OrderState,PaymentDate,UsageDate,Discount,VoucherCode,ExpiryDate")] PurchaseOrder order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            OrderState StatusCache = (OrderState)HttpContext.Session.GetInt32("StatusCache");

            if (StatusCache == OrderState.Offen && order.OrderState == OrderState.Bezahlt)
            {
                order.PaymentDate = DateTime.Today.Date;
            }

            if (StatusCache == OrderState.Bezahlt && order.OrderState == OrderState.Abgeschlossen)
            {
                order.UsageDate = DateTime.Today.Date;
            }

            if (StatusCache == OrderState.Abgeschlossen && order.OrderState == OrderState.Offen)
            {
                order.UsageDate = null;
                order.PaymentDate = null;
            }

            if (StatusCache == OrderState.Bezahlt && order.OrderState == OrderState.Offen)
            {
                order.PaymentDate = null;
            }

            HttpContext.Session.Remove("StatusCache");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "ProductID", order.ProductID);

            return View(order);
        }

        // GET: Bestellungen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Bestellungen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

            _context.PurchaseOrder.Remove(order);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ExtendExpiryDate(int id)
        {
            PurchaseOrder order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

DabesiaWebApp/Views/Orders/Create.cshtml
@model DabesiaWebApp.Models.PurchaseOrder

@{
    ViewData["Title"] = "Erstellen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Erstellen</h2>

<h4>Bestellung</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input type="text" asp-for="OrderDate" value="@(ViewBag.Today)" autocomplete="off" class="form-control datepicker" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderState" class="control-label"></label>
                <select asp-for="OrderState" class="form-control" asp-items="Html.GetEnumSelectList<OrderState>()"></select>
                <span asp-validation-for="OrderState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" value="@(ViewBag.Customer)" class="form-control" asp-items="ViewBag.CustomerID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<form>
    <button asp-action="Index" class="btn btn-default">Zurück zur Bestelliste</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DabesiaWebApp/Views/Orders/CreateSpecific.cshtml
@model DabesiaWebApp.Models.PurchaseOrder

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Erstellen</h2>

<h4>Bestellung</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input type="text" asp-for="OrderDate" value="@(ViewBag.Today)" autocomplete="off" class="form-control datepicker" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderState" class="control-label"></label>
                <select asp-for="OrderState" class="form-control" asp-items="Html.GetEnumSelectList<OrderState>()"></select>
                <span asp-validation-for="OrderState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" value="@(ViewBag.Customer)" class="form-control" asp-items="ViewBag.CustomerID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<form>
    <button asp-action="Index" class="btn btn-default">Zurück zur Bestelliste</button>
    <button asp-action="CustomerOrders" asp-route-id="@(ViewBag.CustomerID)" class="btn btn-default">Zurück zur Bestelllist</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DabesiaWebApp/Views/Orders/Delete.cshtml
@model DabesiaWebApp.Models.PurchaseOrder

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Löschen</h2>
<h4>Bestellung</h4>

<h3>Sind Sie sicher, dass Sie dies tun möchten?</h3>
<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName) @Html.DisplayFor(model => model.Customer.LastName)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderState)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderState)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsageDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsageDate)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VoucherCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VoucherCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderID" />
        <input type="submit" value="Löschen" class="btn btn-danger" />
        <button asp-action="Index" class="btn btn-default">Zurück zu den Bestellungen</button>
    </form>
</div>

DabesiaWebApp/Views/Orders/Details.cshtml
@model DabesiaWebApp.Models.PurchaseOrder

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .blank-row {
        height: 10px !important;
    }

    .blank-column {
        width: 200px !important;
    }

    .bold-td {
        font-weight: bold !important;
    }

    td {
        padding: 5px 0px 5px 0px !important;
    }

    table {
        border-collapse: collapse;
    }
</style>


<h2>Details</h2>

<div>
    <h4>Bestellung</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName) @Html.DisplayFor(model => model.Customer.LastName)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderState)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderState)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UsageDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UsageDate)
        </dd>
    </dl>
    <p />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VoucherCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VoucherCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
    </dl>
</div>

<hr />

<div>
    <form asp-action="ExtendExpiryDate" asp-route-id="@Model.OrderID" mehtod="post">
        <button type="submit" class="btn btn-default">Gutschein um 1 Jahr verlängern</button>
    </form>
</div>
<p />
<div>
    <form asp-controller="File" asp-action="DownloadInvoice" asp-route-id="@Model.OrderID" method="post" enctype="multipart/form-data">
        <button type="submit" class="btn btn-default">Rechnung erstellen</button>
    </form>
</div>
<p />
<div>
    <form asp-controller="File" asp-action="DownloadVoucher" asp-route-id="@Model.OrderID" method="post" enctype="multipart/form-data">
        <button type="submit" class="btn btn-default">Gutschein erstellen</button>
    </form>
</div>
<p />
<div>
    <form>
        <button asp-action="Edit" asp-route-id="@Model.OrderID" class="btn btn-default">Bearbeiten</button>
    </form>
</div>
<hr />
<div>
    <form>
        <button asp-action="Index" asp-route-id="@Model.OrderID" class="btn btn-default">Zurück zu den Bestellungen</button>
    </form>
</div>

DabesiaWebApp/Views/Orders/Edit.cshtml
@model DabesiaWebApp.Models.PurchaseOrder
@{
    ViewData["Title"] = "Bearbeiten";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h2>Edit</h2>
<h4>Bestellung Nr @Html.DisplayFor(b => b.OrderID)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" type="text" id="datepicker" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderState" class="control-label"></label>
                <select asp-for="OrderState" asp-items="Html.GetEnumSelectList<OrderState>()" class="form-control"></select>
                <span asp-validation-for="OrderState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" type="text" id="datepicker" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsageDate" class="control-label"></label>
                <input asp-for="UsageDate" type="text" id="datepicker" class="form-control" />
                <span asp-validation-for="UsageDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" type="text" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoucherCode" class="control-label"></label>
                <input asp-for="VoucherCode" type="text" class="form-control"/>
                <span asp-validation-for="VoucherCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<hr />

<div>
    <form>
        <button asp-action="Details" asp-route-id="@Model.OrderID">Zurück zu Details</button>
        <button asp-action="Index">Zurück zu den Bestellungen</button>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}