DabesiaWebApp/Controllers/OrdersController.cs
using DabesiaWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DabesiaWebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly DabesiaWebAppContext _context;

        public OrdersController(DabesiaWebAppContext context)
        {
            _context = context;
        }

        // GET: Bestellungen
        public async Task<IActionResult> Index(string sortOrder, string searchString, string orderState, DateTime? startDate, DateTime? endDate)
        {
            ViewBag.OrderSortParm = string.IsNullOrEmpty(sortOrder) ? "OrderDesc" : "";
            ViewBag.StateSortParm = sortOrder == "State" ? "StateDesc" : "State";
            ViewBag.DateSortParm = sortOrder == "Date" ? "DateDesc" : "Date";
            ViewBag.CustomerSortParm = sortOrder == "Customer" ? "CustomerDesc" : "Customer";

            IEnumerable<PurchaseOrder> orders = await _context.PurchaseOrder.Include(b => b.Customer).Include(b => b.Product).ToListAsync();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                orders = orders.Where(b =>
                    b.Customer.LastName.ToLower().Contains(searchString.ToLower()) ||
                    b.Customer.FirstName.ToLower().Contains(searchString.ToLower()) ||
                    b.OrderID.ToString().ToLower().Contains(searchString.ToLower()));
                ViewBag.SearchString = searchString;
            }

            if (!string.IsNullOrWhiteSpace(orderState))
            {
                if (orderState != "Alle")
                {
                    orders = orders.Where(b => b.OrderState.ToString() == orderState);
                }
            }

            if (startDate != null)
            {
                if (endDate == null)
                {
                    endDate = DateTime.Today;
                }

                if (startDate <= endDate)
                {
                    orders = orders.Where(b => (b.OrderDate >= startDate && b.OrderDate <= endDate));
                }
                else
                {
                    orders = orders.Where(b => (b.OrderDate <= startDate && b.OrderDate >= endDate));
                }

                ViewBag.StartDate = startDate.Value.Day + "." + startDate.Value.Month + "." + startDate.Value.Year;
                ViewBag.EndDate = endDate.Value.Day + "." + endDate.Value.Month + "." + endDate.Value.Year;
            }

            IOrderedEnumerable<PurchaseOrder> ordersSorted = orders.OrderBy(b => b.OrderID);

            switch (sortOrder)
            {
                case "OrderDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderID);
                    break;
                case "State":
                    ordersSorted = orders.OrderBy(b => b.OrderState);
                    break;
                case "StateDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderState);
                    break;
                case "Date":
                    ordersSorted = orders.OrderBy(b => b.OrderDate);
                    break;
                case "DateDesc":
                    ordersSorted = orders.OrderByDescending(b => b.OrderDate);
                    break;
                case "Customer":
                    ordersSorted = orders.OrderBy(b => b.Customer.LastName);
                    break;
                case "CustomerDesc":
                    ordersSorted = orders.OrderByDescending(b => b.Customer.LastName);
                    break;
                default:
                    break;
            }

            return View(ordersSorted);
        }

        // GET: Bestellungen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Bestellungen/Create
        public IActionResult Create(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.Customer = id;
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID");
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "ProductID");

            ViewBag.Today = DateTime.Today.Day + "." + DateTime.Today.Month + "." + DateTime.Today.Year;

            return View();
        }

        // POST: Bestellungen/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderDate,CustomerID,ProductID,OrderState,PaymentDate,UsageDate,Discount,VoucherCode,ExpiryDate")] PurchaseOrder order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Description", order.ProductID);

            return View(order);
        }

        // GET: Bestellungen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            ViewBag.OrderDate = order.OrderDate;

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "Description", order.ProductID);

            HttpContext.Session.SetInt32("StatusCache", (int)order.OrderState);

            return View(order);
        }

        // POST: Bestellungen/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,OrderDate,CustomerID,ProductID,OrderState,PaymentDate,UsageDate,Discount,VoucherCode,ExpiryDate")] PurchaseOrder order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            OrderState StatusCache = (OrderState)HttpContext.Session.GetInt32("StatusCache");

            if (StatusCache == OrderState.Offen && order.OrderState == OrderState.Bezahlt)
            {
                order.PaymentDate = DateTime.Today.Date;
            }

            if (StatusCache == OrderState.Bezahlt && order.OrderState == OrderState.Abgeschlossen)
            {
                order.UsageDate = DateTime.Today.Date;
            }

            if (StatusCache == OrderState.Abgeschlossen && order.OrderState == OrderState.Offen)
            {
                order.UsageDate = null;
                order.PaymentDate = null;
            }

            if (StatusCache == OrderState.Bezahlt && order.OrderState == OrderState.Offen)
            {
                order.PaymentDate = null;
            }

            HttpContext.Session.Remove("StatusCache");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerID"] = new SelectList(_context.Customer, "CustomerID", "CustomerID", order.CustomerID);
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "ProductID", order.ProductID);

            return View(order);
        }

        // GET: Bestellungen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.PurchaseOrder
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.OrderID == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Bestellungen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

            _context.PurchaseOrder.Remove(order);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ExtendExpiryDate(int id)
        {
            PurchaseOrder order = await _context.PurchaseOrder.SingleOrDefaultAsync(m => m.OrderID == id);

DabesiaWebApp/Controllers/ProductsController.cs
using DabesiaWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DabesiaWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly DabesiaWebAppContext _context;

        public ProductsController(DabesiaWebAppContext context)
        {
            _context = context;
        }

        // GET: Produkte
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Produkte/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Produkte/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produkte/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,Description,Commentary,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Produkte/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Product.SingleOrDefaultAsync(m => m.ProductID == id);
            if (produkt == null)
            {
                return NotFound();
            }
            return View(produkt);
        }

        // POST: Produkte/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,Description,Commentary,Price")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Produkte/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .SingleOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Produkte/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.SingleOrDefaultAsync(m => m.ProductID == id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductID == id);
        }
    }
}

DabesiaWebApp/Views/Shared/_Layout.cshtml
@using  Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dabesia</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
           integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" type="text/css" href="~/css/jquery-ui-themes-1.9.2/themes/cupertino/jquery-ui.css" />

    <script src="https://code.jquery.com/jquery-1.9.1.min.js"
            integrity="sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+rPA0VL2rbQ="
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.9.2/jquery-ui.min.js"
            integrity="sha256-eEa1kEtgK9ZL6h60VXwDsJ2rxYCwfxi40VZ9E0XwoEA="
            crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(function ($) {
            $('.datepicker').datepicker({ dateFormat: 'dd.mm.yy' });
        });
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dabesia</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Customers" asp-action="Index">Kunden</a></li>
                        <li><a asp-area="" asp-controller="Orders" asp-action="Index">Bestellungen</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="Index">Produkte</a></li>
                        <li><a asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DabesiaWebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>